### ISSUE TITLE
Feature Request: Allow creation of rooms without encryption

### ISSUE THREAD

**Issue by edwinsage** [8go/matrix-commander#106]
While it's true that encryption is a good default, there are use cases where creating rooms without encryption is a sensible choice.  For public rooms that are supposed to have a viewable history for new members, encryption causes substantial issues.  Please implement the existing defined `--plain` argument for room-create requests.

**Comment by 8go** [comment]
Done. Incompatible change because stdout output is now different for `--room-create`. See commit notes.

Users can now create rooms and DM rooms without encryption, i.e. with encryption disabled: 
- `matrix-commander --room-create public-room --plain` or 
- `matrix-commander --room-dm-create "@user:server.com" --alias public-room --plain`
