### ISSUE TITLE
Question: how to log out from 'store'?

### ISSUE THREAD

**Issue by hitchhooker** [8go/matrix-commander#150]
root@bkk04  𓅨 ~ ➤ 026450f|master⚡
1804 ± ./matrix_commander/matrix-commander --login password                                                           ⏎ [84d15h29m] ✭
2023-08-17 14:56:28,613:    ERROR: matrix-commander: E225: --login was used but store already exists in 'store'.
2023-08-17 14:56:28,614:     INFO: matrix-commander: 1 error and 0 warnings occurred.

i deleted credentials.json and cant find where this store exists in my machine. logging in with another user seems difficult.

**Comment by 8go** [comment]
The documentation says:

```
The default location for the store directory is a local directory named
`store`. Alternatively, as a secondary choice the program looks for a store
directory in `$HOME/.local/share/matrix-commander/store/`. The user can always
specify a different location via the --store argument. 
```

Remove directory `store` from your local directory. 
Remove directory `store` from `$HOME/.local/share/matrix-commander/store/`. 

Search for all directories called `store` with `find "$HOME" -name "store" -print`. There will be several. Find the *one* that is related to `matrix-commander`. You can verify if the store directory is the one from matrix-commander because if you look inside the directory you will see files that have the name of your Matrix user and your Matrix home server.

Look in the same directory where the credentials file was for a directory called `store` and remove it.
