### ISSUE TITLE
Creating docker image fails on Raspberry Pi

### ISSUE THREAD

**Issue by petmos** [8go/matrix-commander#48]
Hello developers,

I tried to create a docker image as discribed [docker/README.adoc](https://github.com/8go/matrix-commander/blob/master/docker/README.adoc), but it fails with a lot of messages like this:
```
Running transaction
  Preparing        :                                                        1/1 
  Installing       : python3-setuptools-49.1.3-2.fc33.noarch               1/33Error unpacking rpm package python3-setuptools-49.1.3-2.fc33.noarch
 
  Installing       : libmpc-1.1.0-9.fc33.armv7hl                           2/33 
error: unpacking of archive failed on file /usr/bin/easy_install;6113a251: cpio: utime failed - Inappropriate ioctl for device
error: python3-setuptools-49.1.3-2.fc33.noarch: install failed
```
My RaspPi:
```
System Information
------------------

Raspberry Pi 3 Model B Rev 1.2
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

Raspberry Pi reference 2021-03-04
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 461109415073d2eb67083709662ba983cc191f14, stage2

Linux raspberrypi-191 5.10.52-v7+ #1441 SMP Tue Aug 3 18:10:09 BST 2021 armv7l GNU/Linux
Revision	: a02082
Serial		: 00000000d88f6e6a
Model		: Raspberry Pi 3 Model B Rev 1.2
Throttled flag  : throttled=0x50000
Camera          : supported=0 detected=0
```
Because I'm a newbie on dockers I'm not able to fix it for fedora and so I want to ask for help.

But I was able to create a docker image based on the [matrix-nio/docker/Dockerfile](https://github.com/poljar/matrix-nio/blob/master/docker/Dockerfile).
I'm not sure if it's worth to share my Dockerfile or a fix for the current fedora Dockerfile is preferred.

**Comment by 8go** [comment]
Sorry, this is an old issue and I am looking late at this. But it looks like your are mixing up Fedora and Debian. 

From the log file and the errors you are sending and posting here, it looks like you are trying to install Fedora 33 packages on a Debian-based OS. Clearly that cannot work. `apt` for Debian, `dnf` for Fedora, and the packages are all different. 

You need to adjust the `Dockerfile` to your OS. In case of `Debian` you must use `apt` instead of `dnf` and also rename the packages according to the distribution. I hope this points you in the right direction.
